fn main() -> Result<(), f2q::Error> {
    Ok(())
}
